<?php

return [
    'permissions' => [
        'Moderators' => [
            'moderator_list' => 'View Moderatores',
            'moderator_create' => 'Create Moderator',
            'moderator_update' => 'Update Moderator',
            'moderator_delete' => 'Delete Moderator',
        ],
        'Opinions' => [
            'opinion_list' => 'View Opinions',
            'opinion_create' => 'Create Opinion',
            'opinion_update' => 'Update Opinion',
            'opinion_delete' => 'Delete Opinion',
        ],
        'Roles' => [
            'role_list' => 'View Roles',
            'role_view' => 'View Role',
            'role_create' => 'Create Role',
            'role_update' => 'Update Role',
            'role_delete' => 'Delete Role',
        ],
        'Settings' => [
            'setting_view' => 'View Settings',
            'setting_store' => 'Save Settings',
        ],
        'Static Pages' => [
            'page_list' => 'View Pages',
            'page_store' => 'Create Pages',
            'page_edit' => 'Edit Page',
            'page_delete' => 'Delete Page',
            'page_view' => 'View Page',
            'page_update_enable' => 'Enable Disable Page',
        ],
        'Faqs' => [
            'faq_list' => 'View Faqs',
            'faq_store' => 'Create Faqs',
            'faq_edit' => 'Edit Faq',
            'faq_delete' => 'Delete Faq',
            'faq_view' => 'View Faq',
            'faq_update_enable' => 'Enable Disable Faq',
            'faq_update_Arrangment' => 'Update Arrangment Page',
        ],
        'Blog categories' => [
            'blog_category_list' => 'View blog categories',
            'blog_category_store' => 'Create blog categories',
            'blog_category_edit' => 'Edit blog category',
            'blog_category_delete' => 'Delete blog category',
            'blog_category_view' => 'View blog category',
        ],
        'Blog' => [
            'blog_list' => 'View blogs',
            'blog_store' => 'Create blogs',
            'blog_edit' => 'Edit blog',
            'blog_delete' => 'Delete blog',
            'blog_view' => 'View blog',
        ],
        'Packages' => [
            'package_list' => 'View packages',
            'package_store' => 'Create packages',
            'package_edit' => 'Edit package',
            'package_delete' => 'Delete package',
            'package_view' => 'View package',
            'package_cerate_edit_offer' => 'Package Create , Edit Offer',
        ],
        'Exams' => [
            'exam_list' => 'View exams',
            'exam_store' => 'Create exams',
            'exam_edit' => 'Edit exam',
            'exam_delete' => 'Delete exam',
            'exam_view' => 'View exam',
            'exam_update_auto_move' => 'Exam update auto move categories',
        ],
        'Exam Categories' => [
            'exam_category_list' => 'View exam categories',
            'exam_category_store' => 'Create exam categories',
            'exam_category_edit' => 'Edit exam category',
            'exam_category_delete' => 'Delete exam category',
            'exam_category_view' => 'View exam category',
            'exam_category_update_Arrangment'  => 'Update exam category arrangment',
        ],
        'Clients' => [
            'client_list' => 'View Clients',
            'client_create' => 'Create Client',
            'client_update' => 'Update Client',
            'client_delete' => 'Delete Client',
            'client_view' => 'View Client',
        ],
        'Offers' => [
            'offer_list' => 'View offers',
            'offer_create' => 'Create offer',
            'offer_update' => 'Update offer',
            'offer_delete' => 'Delete offer',
        ],
        'Questions' => [
            'question_list' => 'View questions',
            'question_create' => 'Create question',
            'question_update' => 'Update question',
            'question_delete' => 'Delete question',
        ],
        'Answers' => [
            'answer_list' => 'View Answers',
            'answer_create' => 'Create Answer',
            'answer_update' => 'Update Answer',
            'answer_delete' => 'Delete Answer',
            'answer_view' => 'View Answer',
        ],
    ]
];
